### ISSUE TITLE
День 1: базовые навыки

### ISSUE THREAD

**Issue by z-aliakseyeu** [Georgy341/akeera#1]
- [x] сделать консольный скрипт, который выводит на экран консоли что-нибудь ([инфо](http://php.net/manual/ru/features.commandline.usage.php))
- [x] сделать файл `index.php` и [запустить встроенный веб-сервер](http://php.net/manual/ru/features.commandline.webserver.php), проверить, что он работает и выводит на экран то же самое, что и в консоли.
- [x] поменять файл `index.php` таким образом, чтобы при вводе условного адреса: `localhost:8080/index.php?username=George` показывало на экране `Hello, George!` в заголовке `h1`. [вспомогательная информация](http://myblaze.ru/urok-16-php-post-get/)
- [x] вывести на экран текстовое поле, чтобы можно было ввести имя, нажать кнопку и скрипт в ответ показал `Hello, <username>!`, но в адресной строке ничего не поменялось (использовать метод POST)

**Comment by Georgy341** [comment]
Все задания выполнены. Жду нового! ))))
